server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/mytest?useUnicode=true&characterEncoding=utf-8
    username: root
    password: unknown
    driver-class-name: com.mysql.jdbc.Driver
    ## 使用druid
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 0
    host: 192.168.99.100
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
        timeout: 10000

## mybatis 配置
mybatis:
  type-aliases-package: com.jia.model
  mapper-locations: classpath:mapper/*.xml

## 定时任务cron
cron:
  test1: 0/4 * * * * ?
  test2: 0/2 * * * * ?


