server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/mytest?useUnicode=true&characterEncoding=utf-8
    username: root
    password: unknown
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.jia.model
  mapper-locations: classpath:mapper/*.xml